Add `RwLockReadGuard::release`
theseus-os/spin-rs pull request #2
Opened 2023-04-23 00:37 UTC by tsoutsman

2023-04-24 18:31 UTC, kevinaboos requested changes
Thanks! Can you explain here (or better yet, add a comment that explains) why you're modifying the UPGRADED bit in the new `release()` function? That seems a bit odd to me, since I'm not sure why a non-upgradable read lock would want to mess with that bit.

2023-04-25 05:07 UTC, tsoutsman commented
That's a mistake. I also didn't forget `self`; not my finest work :/.

I added a basic test to make sure everything works.

2023-04-25 17:17 UTC, kevinaboos requested changes
Thanks, looks good. Since this PR includes a bunch of upstream commits that we want to preserve, I'd like to merge it rather than squash or rebase it. To avoid having buggy commits, can you squash your latest two commits into one? That is, squash c0d21a4 into 4c97347

2023-04-26 00:19 UTC, kevinaboos approved these changes

2023-04-26 00:20 UTC, merged